import HeroSection from './component/HeroSection';
import Navbar from './component/Navbar';
import AboutSection from './component/AboutSection';
import ProjectsSection from './component/ProjectsSection';
import EmailSection from './component/EmailSection';
import Footer from './component/Footer';
import AchievementSection from './component/AchievementSection';

export default function Home() {
  return (
    <main className="flex min-h-screen justify-center items-center flex-col bg-black">
        <Navbar/>
      <div className="container mt-24 mx-auto px-12 py-4">
        <HeroSection/>
        <AchievementSection/>
        <AboutSection/>
        <ProjectsSection/>
        <EmailSection/>
      </div>
        <Footer/>
    </main>
  )
}
export const metadata = {
  title: "rzwn",
  description: "Generated by Create Next App",
};
